name: Exercise linting with PHPCS for PSR 12

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: PHPCS Linting - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.2]
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - uses: shivammathur/setup-php@6d7209f44a25a59e904b1ee9f3b0c33ab2cd888d
        with:
          php-version: ${{ matrix.php-version }}
          extensions: gmp
          tools: composer

      - name: Install composer packages
        run: CI="true" composer install

      - name: Lint exercises
        shell: bash
        run: composer lint:check
